import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="espacamento-h1">
            <img src="logo.jpeg" height={100} width={100} alt="Logo" />
            <h1>CT GLADIADORES</h1>
          </div>

          <div className="divespacamentodelinhas">
            <a className="espaçamento" href="http://localhost:3000/usuario">Pagina inicial</a>
            <a className="espaçamento" href="https://www.google.com/?hl=pt-BR">Agenda</a>
  
            <Link href="/aluno">Aluno</Link>
            <a className="espaçamento" href="https://www.google.com/?hl=pt-BR" style={{ color: 'gray' }}>Mensalidade</a>
          </div>

          <button className="logout-button">
            Log out
          </button>
        </header>
        {children}
      </body>
    </html>
  );
}
