/*import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header> 
          <h1>
            <img src = "logo.jpeg" width={80}/>ACADEMIA GLADIADORES 
            <a href="https://www.google.com" >Página inicial</a> 
            <a href="https://www.youtube.com">Agenda</a>
        </h1> 
    
        </header>{children}
      </body>
    </html>
  );
}*/

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'${geistSans.variable} ${geistMono.variable}'}>
        <header> 
          <h1><img src = "logo.jpeg" height={50} width={50}/>ACADEMIA GLADIADORES <a href="http://localhost:3000/usuario" style={{ color: 'gray' }}>| Pagina inicial</a> <a href="https://www.google.com/?hl=pt-BR" >| Agenda</a> <a href="https://www.google.com/?hl=pt-BR">| Treino</a> <a href="http://localhost:3001/mensalidade" style={{ color: 'white' }}>| Mensalidade</a></h1> 

        </header>{children}
      </body>
    </html>
  )}