import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header> 
          <h1>
            <img src = "logo.jpeg" width={80}/>ACADEMIA GLADIADORES 
            <a href="https://www.google.com" >Página inicial</a> 
            <a href="https://www.youtube.com">Agenda</a>
        </h1> 
    
        </header>{children}
      </body>
    </html>
  );
}
